BASE: ['']

DATALOADER:
  DATASET: "iBVP"
  CACHED_PATH: "/home/acir/Documents/rppg-datasets/ibvp/cached/fixedface_bbox1.5_resize128x128"
  FPS: 30

INFERENCE:
  METHOD_NAME: "rhythmformer"
  DEVICE: "cuda:0"
  BATCH_SIZE: 4
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 160
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 60
  INPUT_FRAME_SIZE: (128, 128)
  INPUT_FRAMES_NUM: 160
  INPUT_TYPE: ["standardized"]
  LABEL_TYPE: "standardized"
  INPUT_FORMAT: "NDCHW"