BASE: ['']

DATALOADER:
  DATASET: "MAHNOB"
  RAW_PATH: None
  CACHED_PATH: "/home/acir/Documents/rppg-datasets/mahnob/cached/fixedface_bbox1.5_resize128x128"
  FPS: 61

INFERENCE:
  METHOD_NAME: "unsupervised"
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 300
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 30