BASE: ['']

DATALOADER:
  DATASET: "PURE"
  CACHED_PATH: "/home/acir/Documents/rppg-datasets/pure/cached/fixedface_bbox1.5_resize72x72"
  FPS: 30

INFERENCE:
  METHOD_NAME: "physnet"
  DEVICE: "cuda:0"
  BATCH_SIZE: 4
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 128
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 30
  INPUT_FRAME_SIZE: (72, 72)
  INPUT_FRAMES_NUM: 128
  INPUT_TYPE: ["diffnormalized"]
  LABEL_TYPE: "diffnormalized"
  INPUT_FORMAT: "NCDHW"