BASE: ['']

DATALOADER:
  DATASET: "UBFC-rPPG"
  CACHED_PATH: "/home/acir/Documents/rppg-datasets/ubfc-rppg/cached/fixedface_bbox1.5_resize128x128"
  FPS: 30

INFERENCE:
  METHOD_NAME: "physformer"
  DEVICE: "cuda:0"
  BATCH_SIZE: 4
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 160
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 30
  INPUT_FRAME_SIZE: (128, 128)
  INPUT_FRAMES_NUM: 160
  INPUT_TYPE: ["diffnormalized"]
  LABEL_TYPE: "diffnormalized"
  INPUT_FORMAT: "NCDHW"
