BASE: ['']

DATALOADER:
  DATASET: "MAHNOB"
  RAW_PATH: "/mnt/16TB/rppg-datasets/mahnob/raw/Sessions"
  CACHED_PATH: "/mnt/16TB/rppg-datasets/mahnob/cached/fixedface_bbox1.5_resize72x72"
  FPS: 61

PRE_PROCESSING:
  RESIZE:
    W: 72
    H: 72