BASE: ['']

DATALOADER:
  DATASET: "MAHNOB"
  RAW_PATH: "/mnt/16TB/rppg-datasets/mahnob/raw/Sessions"
  CACHED_PATH: "/mnt/16TB/rppg-datasets/mahnob/cached/fixedface_bbox1.5_resize128x128"
  FPS: 61

PRE_PROCESSING:
  RESIZE:
    W: 128
    H: 128