BASE: ['']

DATALOADER:
  DATASET: "PURE"
  RAW_PATH: "/mnt/16TB/rppg-datasets/pure/raw"
  CACHED_PATH: "/mnt/16TB/rppg-datasets/pure/cached/fixedface_bbox1.5_resize72x72"
  FPS: 30

PRE_PROCESSING:
  RESIZE:
    W: 72
    H: 72