BASE: ['']

DATALOADER:
  DATASET: "UBFC-Phys"
  RAW_PATH: "/mnt/16TB/rppg-datasets/ubfc-phys/raw"
  CACHED_PATH: "/mnt/16TB/rppg-datasets/ubfc-phys/cached/fixedface_bbox1.5_resize128x128"
  FPS: 35

PRE_PROCESSING:
  RESIZE:
    W: 128
    H: 128