BASE: ['']

POST_PROCESSING:
  BANDPASS: True
  BANDPASS_LOW_FREQ: 45
  BANDPASS_HIGH_FREQ: 150 
  FREQ_RESOLUTION: 2 

CONFIDENCE_MODEL:
  BANDPASS: True
  BANDPASS_LOW_FREQ: 45
  BANDPASS_HIGH_FREQ: 300 
  FREQ_RESOLUTION: 2 