BASE: ['']

DATALOADER:
  DATA_FORMAT: "NDHWC"
  DATASET: "MAHNOB"
  RAW_PATH: "/hdd1/rppg-datasets/mahnob/raw/Sessions"
  CACHED_PATH: "/hdd1/rppg-datasets/mahnob/cached/fixedface_bbox1.5_resize128x128"
  FPS: 61

PRE_PROCESSING:
  CROP_FACE:
    DO_CROP_FACE: True
    BACKEND: "MTCNN"
    USE_LARGE_FACE_BOX: True
    LARGE_BOX_COEF: 1.5
    DO_DYNAMIC_DETECTION: False
  RESIZE:
    W: 128
    H: 128