BASE: ['']

DATALOADER:
  DATA_FORMAT: "NDHWC"
  DATASET: "PURE"
  RAW_PATH: "/hdd2/rppg-datasets/pure/raw"
  CACHED_PATH: "/hdd2/rppg-datasets/pure/cached/fixed_face_128x128"
  FPS: 30

INFERENCE:
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 300
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 30

POST_PROCESSING:
  BANDPASS: True
  BANDPASS_LOW_FREQ: 45
  BANDPASS_HIGH_FREQ: 150 
  FREQ_RESOLUTION: 2 

CONFIDENCE_MODEL:
  BANDPASS: True
  BANDPASS_LOW_FREQ: 45
  BANDPASS_HIGH_FREQ: 300
  FREQ_RESOLUTION: 2
