BASE: ['']

DATALOADER:
  DATA_FORMAT: "NDHWC"
  DATASET: "Selfies-and-Videos"
  RAW_PATH: "/hdd1/selfies-and-videos/raw"
  CACHED_PATH: "/hdd1/selfies-and-videos/cached/test"
  FPS: 30

PRE_PROCESSING:
  CROP_FACE:
    DO_CROP_FACE: True
    BACKEND: "MTCNN"
    USE_LARGE_FACE_BOX: True
    LARGE_BOX_COEF: 1.5
    DO_DYNAMIC_DETECTION: False
  RESIZE:
    W: 128
    H: 128

INFERENCE:
  CHUNK:
    DO_CHUNK: True
    CHUNK_LENGTH: 300
    CHUNK_OVERLAP: True
    CHUNK_OVERLAP_STEP: 30
