BASE: ['']
DATALOADER:
  DATASET: "UBFC-rPPG"
  RAW_PATH: "/hdd2/rppg-datasets/ubfc-rppg/raw"
  CACHED_PATH: "/hdd2/rppg-datasets/ubfc-rppg/cached/fixedface_bbox1.5_resize128x128"
  FPS: 30

PRE_PROCESSING:
  CROP_FACE:
    DO_CROP_FACE: True
    BACKEND: "MTCNN"
    USE_LARGE_FACE_BOX: True
    LARGE_BOX_COEF: 1.5
    DO_DYNAMIC_DETECTION: False
  RESIZE:
    W: 128
    H: 128